version: "3.7"
services:
  app:
    build:
      args:
        user: matei
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: booky
    container_name: booky-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www

  mariadb:
    image: mariadb
    container_name: booky-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mariadb:/docker-entrypoint-initdb.d
      - ./docker-compose/volume:/var/lib/mysql

  nginx:
    image: nginx:1.17-alpine
    container_name: booky-nginx
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    expose:
      - "80"
    volumes:
      - ../:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d